import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import { Header } from './layout/Header/Header';
import { Footer } from './layout/Footer/Footer';
import { Sidebar } from './layout/Sidebar/Sidebar';
import styles from './layout/Layout.module.css';

const NotoSans = Noto_Sans_KR({
  subsets: ['latin'],
  weight: "500"
});

export const metadata: Metadata = {
  title: 'Top App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
      <html lang="ru">
        <body className={NotoSans.className}>
          <div className={styles.wrapper}>
            <Header className={styles.header} />
            <Sidebar className={styles.sidebar} />
            <div className={styles.body}>
              {children}
            </div>
            <Footer className={styles.footer} />
          </div>
        </body>
      </html>
  )
}