import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import { TheHeader } from '@/components/TheHeader';
import { Footer } from '@/components/Footer';

const NotoSans = Noto_Sans_KR({
  subsets: ['latin'],
  weight: "500"
});

export const metadata: Metadata = {
  title: 'Top App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={NotoSans.className}>
        <TheHeader />
        {children}
        <Footer />
      </body>
    </html>
  )
}
